# This file is used to configure the Travis CI tests for this repository

matrix:
  include:
    - name: "Spell Check"
      language: python
      python: 3.6
      install:
        # Install codespell
        # https://github.com/codespell-project/codespell
        - pip install codespell

      script:
        - codespell --skip="${TRAVIS_BUILD_DIR}/.git" --ignore-words="${TRAVIS_BUILD_DIR}/etc/codespell-ignore-words-list.txt" "$TRAVIS_BUILD_DIR"

notifications:
  email:
    on_success: always
    on_failure: always
  webhooks:
    urls:
      # Use TravisBuddy to automatically comment on any pull request that results in a failing CI build
      - https://www.travisbuddy.com/
    on_success: never
    on_failure: always
